name: build-linux-x64
on:
  push:
  workflow_call:
jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Vulkan
        run: sudo apt install libvulkan-dev -y
      - name: Install vulkan-validation-layers
        run: sudo apt install vulkan-validationlayers-dev -y
      - name: Install spirv-tools
        run: sudo apt install spirv-tools -y

      - name: Install glfw3
        run: sudo apt install libglfw3-dev -y
      - name: Install glm
        run: sudo apt install libglm-dev -y

      - name: Install Xxf, Xi
        run: sudo apt install libxxf86vm-dev libxi-dev -y

      - name: Cache Glslc Executable
        id: cache-glslc-bin
        uses: actions/cache@v3
        with:
          path: ./glslc
          key: glslc-bin

      - name: Download glslc
        if: steps.cache-glslc-bin.outputs.cache-hit != 'true'
        run: |
          curl https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_gcc_release/382/20220602-094524/install.tgz --output install.tgz
          tar -xf install.tgz
          mv install/bin/glslc ./
          rm -rf install
      
      - name: Install glslc
        run: sudo cp ./glslc /usr/local/bin/

      - name: Cmake
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Pre Upload Artifact Process
        run: cp ./build/bin/app ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ikulab-motion-viewer-linux-x64
          path: |
            ./app
            ./shaders/
            ./models/
            ./fonts