name: build-x64-Windows
on:
  push:
  workflow_call:
jobs:
  build-x64-Windows:
    runs-on: windows-latest
    steps:

    - run: dir "C:\Program Files"
    - run: dir "C:\Program Files\Microsoft Visual Studio"
    - run: dir "C:\Program Files\Microsoft Visual Studio\2022"
    - run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
    - run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC"
