name: build-linux-x64
on:
  # push:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install vulkan
        run: sudo apt install libvulkan-dev -y
      - name: install vulkan-validation-layers
        run: sudo apt install vulkan-validationlayers-dev -y
      - name: install spirv-tools
        run: sudo apt install spirv-tools -y

      - name: install glfw3
        run: sudo apt install libglfw3-dev -y
      - name: install glm
        run: sudo apt install libglm-dev -y

      - name: install Xxf and Xi
        run: sudo apt install libxxf86vm-dev libxi-dev -y

      - name: cache glslc executable
        id: cache-glslc-bin
        uses: actions/cache@v3
        with:
          path: ./glslc
          key: glslc-bin

      - name: download glslc
        if: steps.cache-glslc-bin.outputs.cache-hit != 'true'
        run: |
          curl https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/linux/continuous_gcc_release/382/20220602-094524/install.tgz --output install.tgz
          tar -xf install.tgz
          mv install/bin/glslc ./
          rm -rf install
      
      - name: install glslc
        run: sudo cp ./glslc /usr/local/bin/

      - name: cmake
        run: |
          cmake -S . -B build
          cmake --build build

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ikulab-motion-viewer-linux-x64
          path: ./build/bin/app