name: build-x64-Windows
on:
  push:
  workflow_call:
jobs:
  build-x64-Windows:
    runs-on: windows-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'
          cache: 'pip' # caching pip dependencies

      - name: Setup python packages
        run: pip install -r requirements.txt

      - name: Build Version Checker
        run: subprojects/version_checker/build.ps1

      - name: Build vc++ installer script
        run: subprojects/vcpp_installer/build.ps1

      - name: Install Ninja
        run: choco install ninja

      - name: Setup VisualStudio Dev Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache vcpkg_installed
        uses: actions/cache@v4
        with:
          path: ./build_release_windows/vcpkg_installed
          key: ${{ runner.os }}-${{ runner.arch }}-vcpkg-${{ hashFiles('./vcpkg.json', './core/ikura/vcpkg.json') }}

      - name: save VC++ version file
        run: bash ./scripts/create_vcpp_version_file.sh

      - name: copy vc_redist.*.exe
        run: bash ./scripts/copy_vc_redist_exe.sh

      - name: Install NSIS Plugin for x86-ansi
        run: |
          cp `
          ./subprojects/windows_installer/NsisPlugin/AccessControl_x86_ansi.dll `
          "C:/Program Files (x86)/NSIS/Plugins/x86-ansi/AccessControl.dll"

      - name: Install NSIS Plugin for x86-unicode
        run: |
          cp `
          ./subprojects/windows_installer/NsisPlugin/AccessControl_x86_unicode.dll `
          "C:/Program Files (x86)/NSIS/Plugins/x86-unicode/AccessControl.dll"

      - name: Build
        run: ./scripts/build_win_package.ps1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ikulab-motion-viewer-x64-windows
          path: |
            ./ikulab-motion-viewer_Installer.exe
