name: build-x64-Windows
on:
  push:
  workflow_call:
jobs:
  build-x64-Windows:
    runs-on: windows-latest
    steps:

      - run: bash test.sh

#      - name: Checkout Code
#        uses: actions/checkout@v3
#        with:
#          submodules: recursive
#
#      - name: Install Ninja
#        run: choco install ninja
#
#      - name: Setup VisualStudio Dev Environment
#        uses: ilammy/msvc-dev-cmd@v1
#
#      - name: Cache vcpkg_installed
#        uses: actions/cache@v2
#        with:
#          path: ./build_release/vcpkg_installed
#          key: ${{ runner.os }}-${{ runner.arch }}-vcpkg-${{ hashFiles('./vcpkg.json', './core/ikura/vcpkg.json') }}
#
#      - name: Build
#        run: utils/scripts/build_win_package.ps1
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ikulab-motion-viewer-x64-windows
#          path: |
#            ./ikulab-motion-viewer_Installer.exe
