name: build-x64-Windows
on:
  push:
  workflow_call:
jobs:
  build-x64-Windows:
    runs-on: windows-latest
    steps:

    - name: test
      run: echo "Hello, World!"

    - name: dir
      run: dir C:\