name: release
on: [workflow_dispatch]
  # release:
  #   types: [published]
  # workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build-linux-x64.yml
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: hello
        run: echo hello