name: release-binary
on:
  release:
    types: [published]
  workflow_dispatch:
  push: # for debug
jobs:
  build:
    uses: ./.github/workflows/build-linux-x64.yml
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: download artifact
      uses: actions/download-artifact@v3

    - name: upload to release page
      run: |
        hub release create \
          -a ./ikulab-motion-viewer-linux-x64
          -m "this is test release"
          ${{ github.event.head_commit.message }}