name: release-binary
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-linux-x64.yml
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: download artifact
      uses: actions/download-artifact@v3

    - name: upload to release page
      run: |
        hub release create \
          -a ./ikulab-motion-viewer-linux-x64/app \
          -m "this is test release" \
          test_${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}