name: release-binary
on:
  release:
    types: [published]
  workflow_dispatch:
  push: # for debug
jobs:
  build:
    uses: ./.github/workflows/build-linux-x64.yml
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: message
        run: echo "build done"